server:
  port: 8087

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG

management:
  server:
    port: 8096
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

springdoc:
  packagesToScan: uk.gov.justice.laa.crime.crowncourt
  show-actuator: true
  api-docs:
    path: /crown-court-proceeding
    enabled: true

  swagger-ui:
    path: /open-api/docs.html
    enabled: true
    operationsSorter: method

spring:
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST_PORT}/${DATASOURCE_DBNAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 3600000

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false

  security:
    oauth2:
      client:
        provider:
          maatapi:
            token-uri: ${MAAT_API_OAUTH_URL}
          cda:
            token-uri: ${CDA_OAUTH_URL}
        registration:
          maatapi:
            client-id: ${MAAT_API_OAUTH_CLIENT_ID}
            client-secret: ${MAAT_API_OAUTH_CLIENT_SECRET}
            authorization-grant-type: client_credentials
          cda:
            clientId: ${CDA_OAUTH_CLIENT_ID}
            clientSecret: ${CDA_OAUTH_CLIENT_SECRET}
            authorizationGrantType: client_credentials
      resourceserver:
        jwt:
          issuer-uri: ${crown-court-proceeding.security.issuer-uri}
sentry:
  dsn: ${SENTRY_DSN}
  environment: ${SENTRY_ENV}
  release: 0.0.1
  servername: aws-eks-container
  send-default-pii: true
  attach-stacktrace: true
  sample-rate: 0.05

retry-config:
  max-retries: 3
  min-back-off-period: 5
  jitter-value: 0.75

cloud-platform:
  aws:
    sqs:
      region: ${CLOUD_PLATFORM_QUEUE_REGION}
      accesskey: ${CLOUD_PLATFORM_QUEUE_ACCESS_KEY}
      secretkey: ${CLOUD_PLATFORM_QUEUE_SECRET_KEY}
      queue:
        hearingResulted: ${HEARING_RESULTED_QUEUE}
        prosecutionConcluded: ${PROSECUTION_CONCLUDED_QUEUE}

crown-court-proceeding:
  security:
    issuer-uri: http://localhost:${server.port}

maatApi:
  oAuthEnabled: true
  baseUrl: ${MAAT_API_BASE_URL}
  assessments-domain: /api/internal/v1/assessment
  ioj-appeal-endpoints:
    find-url: ${maatApi.assessments-domain}/ioj-appeal/repId/{repId}/current-passed
  rep-order-endpoints:
    find-url: ${maatApi.assessments-domain}/rep-orders/{repId}
    update-url: ${maatApi.assessments-domain}/rep-orders
  graphql-endpoints:
    graphql-query-url: ${maatApi.assessments-domain}/graphQL
  offence:
    find-url: ${maatApi.assessments-domain}/offence/case/{caseId}
    offence-count-url: ${maatApi.assessments-domain}/offence/{offenceId}/case/{caseId}
  wq-hearing-endpoints:
    find-url: ${maatApi.assessments-domain}/wq-hearing/{hearingUUID}/maatId/{maatId}
  wq-link-register-endpoints:
    find-url: ${maatApi.assessments-domain}/wq-link-register/{maatId}
  wq-offence:
    offence-count-url: ${maatApi.assessments-domain}/wq-offence/{offenceId}/case/{caseId}
  xlat-result:
    result-codes-for-cc-imprisonment-url: ${maatApi.assessments-domain}/xlat-result/cc-imprisonment
    result-codes-for-cc-bench-warrant-url: ${maatApi.assessments-domain}/xlat-result/cc-bench-warrant
    result-codes-for-wqtype-subtype-url: ${maatApi.assessments-domain}/xlat-result/wqType/{wqType}/subType/{subType}
  result:
    result-codes-by-caseid-asnseq-url: ${maatApi.assessments-domain}/result/caseId/{caseId}/asnSeq/{asnSeq}
  wq-result:
    result-codes-by-caseid-asnseq-url: ${maatApi.assessments-domain}/wq-result/caseId/{caseId}/asnSeq/{asnSeq}
  crown-court-stored-procedure:
    update-crown-court-outcome-url: ${maatApi.assessments-domain}/crown-court/updateCCOutcome
  crown-court-processing:
    update-appeal-cc-sentence-url: ${maatApi.assessments-domain}/crown-court/update-appeal-cc-sentence
    update-cc-sentence-url: ${maatApi.assessments-domain}/crown-court/update-cc-sentence

cda:
  url: ${CDA_BASE_URL}
  laastatus:
    url: "/api/internal/v1/representation_orders"
  hearing:
    url: "/api/internal/v2/hearing_results/{hearingId}"

feature:
  postMvp:
    enabled: false
